import { LayoutWrapper } from "@/components/LayoutWrapper";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <LayoutWrapper id="error-404">{children}</LayoutWrapper>;
}
